import { createAction } from 'redux-starter-kit'

export const setUser = createAction('SET_USER')
export const removeUser = createAction('REMOVE_USER')
export const setVehicles = createAction('SET_VEHICLES')
export const setVehicle = createAction('SET_VEHICLE')
export const setSpots = createAction('SET_SPOTS')
export const setAis = createAction('SET_AIS')
export const setPlans = createAction('SET_PLANS')
export const deleteWp = createAction('DELETE_WP')
export const updateWpLocation = createAction('UPDATE_WP_LOCATION')
export const addWpToPlan = createAction('ADD_WP_TO_PLAN')
export const editPlan = createAction('EDIT_PLAN')
export const cancelEditPlan = createAction('CANCEL_EDIT_PLAN')
export const addNewPlan = createAction('ADD_NEW_PLAN')
export const savePlan = createAction('SAVE_PLAN')
export const setProfiles = createAction('SET_PROFILES')
export const setSlider = createAction('SET_SLIDER')
export const setSelectedWaypointIdx = createAction('SET_SELECTED_WAYPOINT')
export const setToolSelected = createAction('SET_TOOL_SELECTED')
